### ISSUE TITLE
extenders throw exception after postback

### ISSUE THREAD

**Issue by lianbo** [appendto/juiceui#13]
when page is postback, the juice extender will throw exception.(juice control works good).
It is because that when redering the widget option to page, the extender use target control’s id as the id, see line 341 in JuiceWidgetState:
id = widgetHash.TargetControl.ClientID

But when loading the option from jsonState when postback, It use Widget.ClientID, see line 132
var postedControlState = LoadPostDataForControl(Widget.Page, Widget.ClientID);

I'm not sure whether they want to loadpostdata if it is an extender.
If not, I think maybe this issue can be fixed like this,
 (line 146, JuiceWidgetState.cs)  if(value != currentValue) { 
to new code: if(value != currentValue && value != null) {

**Comment by shellscape** [comment]
Specifically, which extender control were you using? Test-case code would be much appreciated.

**Comment by lianbo** [comment]
Steps to reproduce this issue,
1. Open whichever extender's sample of "Juice Test Site" and add a asp:Button to it.
2. Run the sample page.
3. Click the button to postback the page
This issue will be observed.

**Comment by shellscape** [comment]
I'm not seeing a generic issue on all of the extenders on the current source tree, and the original issue reported is too encompassing with too little information. If specific exceptions occur on specific controls, please:
- make sure you're running on the current source tree.
- open one issue per control.
- include all exception information.
