### ISSUE TITLE
Password for JuiceUI.pfx

### ISSUE THREAD

**Issue by howardhw** [appendto/juiceui#15]
After download the juice source and build it, we found that it needs a password for JuiceUI.pfx. How can I do this? 
Thanks!

**Comment by shellscape** [comment]
The pfx is the file which allows us to sign the assembly. We currently have no plans to make the password public, however, if you're building for your own use, simply Exclude the file from the project and it should build normally. Let us know if you have any issues after Excluding it.

**Comment by howardhw** [comment]
Thanks for your reply. How can i get the signed dll?

**Comment by shellscape** [comment]
We'll be releasing 0.9.1.1 today with the signed assembly. If you're on twitter you can follow us @juiceui.
