### ISSUE TITLE
Hard dependency on version of jquery and jquery.ui

### ISSUE THREAD

**Issue by suhasj** [appendto/juiceui#25]
Currently juiceui is dependent on jquery=1.7.1 and jquery.ui=1.8.18. If the project has the latest jquery package installed which is 1.7.2, then installation of JuiceUI package fails.

Possible fix: Make the dependency for jquery as >=1.7 && <1.8 
and for jquery.ui >= 1.8.18 && <1.8.19

**Comment by shellscape** [comment]
resolved with 0.9.2
