### ISSUE TITLE
Juice UI 1.0.1 error

### ISSUE THREAD

**Issue by rodrigosalazar** [appendto/juiceui#29]
The JuiceApp.cs references to  jquery-ui-1.9.0pre.custom.js but NuGet downloads jquery-ui-1.8.24.js instead. This makes juice.js throws an " 'datepicker._attachDatepicker' is null or not an object" error.

I only include these lines in a blank web form:

```
<asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
<asp:TextBox runat="server" ID="TextBox1" />
<Juice:Datepicker ID="Datepicker1" runat="server" TargetControlID="TextBox1" />
```

**Comment by shellscape** [comment]
The release version (the library that is shipped in NuGet with version 1.0.1) does not reference that file. 1.9.0pre is only referenced within the current in-development code on the master branch.
