### ISSUE TITLE
NuGet Installation failing

### ISSUE THREAD

**Issue by rjdudley** [appendto/juiceui#6]
Using VS 2010 SP1 Ultimate, the NuGet package is failing.  Here is what I see in the package manager console:

PM> Install-Package JuiceUI
Install-Package : Object reference not set to an instance of an object.
At line:1 char:16
- Install-Package <<<<  JuiceUI
  - CategoryInfo          : NotSpecified: (:) [Install-Package], NullReferenceException
  - FullyQualifiedErrorId : System.NullReferenceException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by shellscape** [comment]
I'm unable to reproduce the problem here, successfully installed through both the console and gui: http://gyazo.com/bf47e3be8336ac5cd5e201218e264709.png?1330454739

Please open this thread on the Google Group (http://groups.google.com/group/juiceui) for discussion and troubleshooting.

**Comment by shellscape** [comment]
Marking as closed due to inactivity. Please reopen if the issue persists.
